Sebastian Raschka, 2015  
`mlxtend`, a library of extension and helper modules for Python's data analysis and machine learning libraries

- GitHub repository: https://github.com/rasbt/mlxtend
- Documentation: http://rasbt.github.io/mlxtend/

View this page in [jupyter nbviewer](http://nbviewer.ipython.org/github/rasbt/mlxtend/blob/master/docs/sources/_ipynb_templates/_template.ipynb)

In [1]:
%load_ext watermark
%watermark -a 'Sebastian Raschka' -u -d -v -p matplotlib,numpy,scipy,mlxtend

Sebastian Raschka 
last updated: 2016-01-30 

CPython 3.5.1
IPython 4.0.3

matplotlib 1.5.1
numpy 1.10.2
scipy 0.16.1
mlxtend 0.3.0


# Shuffle Arrays in Unison

A function for NumPy arrays in unison.

> from mlxtend.preprocessing import shuffle_arrays_unison

### Related Topics

- [Standardize](./standardize.md)
- [MeanCenterer](./mean_centerer.md)
- [Min-Max Scaling](./minmax_scaling.md)
- [DenseTransformer](./scikit-learn_dense_transformer.md)

# Examples

## Example 1 - Scaling a Pandas DataFrame

In [2]:
import numpy as np
from mlxtend.preprocessing import shuffle_arrays_unison
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 2, 3])
print('X:\n%s' % X)
print('y:\n%s' % y)

X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
y:
[1 2 3]


In [3]:
X2, y2 = shuffle_arrays_unison(arrays=[X, y], random_state=3)
print('X2:\n%s' % X2)
print('y2:\n%s' % y2)

X2:
[[4 5 6]
 [1 2 3]
 [7 8 9]]
y2:
[2 1 3]


# API

In [5]:
with open('../../api_modules/mlxtend.preprocessing/shuffle_arrays_unison.md', 'r') as f:
    print(f.read())

## shuffle_arrays_unison

*shuffle_arrays_unison(arrays, random_state=None)*

Shuffle NumPy arrays in unison.

**Parameters**

- `arrays` : array-like, shape = [n_arrays]

    A list of NumPy arrays.

- `random_state` : int (default: None)

    Sets the random seed.

**Returns**

- `shuffled_arrays` : A list of NumPy arrays after shuffling.


**Examples**

    >>> import numpy as np
    >>> from mlxtend.preprocessing import shuffle_arrays_unison
    >>> X1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    >>> y1 = np.array([1, 2, 3])
    >>> X2, y2 = shuffle_arrays_unison(arrays=[X1, y1], random_state=3)
    >>> assert(X2.all() == np.array([[4, 5, 6], [1, 2, 3], [7, 8, 9]]).all())
    >>> assert(y2.all() == np.array([2, 1, 3]).all())
    >>>


